name: nl-housing
channels: [conda-forge]
dependencies:
  - python=3.11
  - pandas>=2.2
  - pyarrow>=17.0
  - pyyaml>=6.0
  - scikit-learn>=1.5
  - matplotlib>=3.8
  - numpy>=2.1
  - streamlit>=1.38
  - pip
  - pip:
      - kaggle>=1.6
